use_frameworks!

target 'BHResting_Example' do
  pod 'BHResting', :path => '../'

  target 'BHResting_Tests' do
    inherit! :search_paths
    pod 'BHResting', :path => '../'
    pod 'Quick', '~> 1.0.0'
    pod 'Nimble', '~> 5.1.1'
  end
end
